### ISSUE TITLE
Enable some features for EVM tokens

### ISSUE THREAD

**Issue by Sokol142196** [openbitdev/OpenBit-Wallet#102]
**Describe the task**
Enable some features for EVM tokens

- [x] Allow get address: https://github.com/openbitdev/OpenBit-Wallet/issues/93
  - Actual: Can not get address (show Select token screen is empty)
  - Expect: Allow get address
=> will be fixed in #64 

- [x] Allow Send fund
  - Actual: Do not show token to choose to send
  - Expect: Show token on list to choose token
=> will be fixed in #64 

- [x] #149
- [x] Allow send collectible => Related to issue #161
- [x] Allow import EVM network (already implemented) => Related to issue #54
